### ISSUE TITLE
JitPack上已经找不到MMKV-KTX了，是什么原因呢？删库了吗？

### ISSUE THREAD

**Issue by ljiezhou** [DylanCaiCoding/MMKV-KTX#11]
![Snipaste_2024-11-27_15-16-21](https://github.com/user-attachments/assets/a32027f0-c896-43f8-92d3-7fb73aa2fc99)

**Comment by DylanCaiCoding** [comment]
没删，是不是搜错了

另外，发了 2.0.1 版本能支持 map 用法，可以升级一下

<img width="659" alt="image" src="https://github.com/user-attachments/assets/06ccf777-4da3-4e58-a312-474aa9068534">
