### ISSUE TITLE
如果要存集合怎么办

### ISSUE THREAD

**Issue by renhuan** [DylanCaiCoding/MMKV-KTX#2]

**Comment by DylanCaiCoding** [comment]
转成 Json 保存。或者可以写一个继承 Parcelable 的类持有集合，但是感觉使用更麻烦。

**Comment by renhuan** [comment]
> 转成 Json 保存。或者可以写一个继承 Parcelable 的类持有集合，但是感觉使用更麻烦。

那一般就是json保存呗

**Comment by DylanCaiCoding** [comment]
嗯嗯
