### ISSUE TITLE
提个bug

### ISSUE THREAD

**Issue by ljphawk** [DylanCaiCoding/MMKV-KTX#5]
MMKVProperty中有private var cache: V? = null，并在set和get中对其赋值，这是个比较好的优化方案，但我如果使用了removeValueForKey的话，并不会去清空cache的值，会导致清空了也一直返回上次保存或者上次获取到的值。

**Comment by DylanCaiCoding** [comment]
想了下不好改，目前不能用 `kv.removeValueForKey(key)`，要清理数据的话给委托属性赋值为 null 或 默认值，其实赋值的代码比 `kv.removeValueForKey(key)` 简洁一点。主要受影响的是用不了 `kv.clearAll()` 没那么方便，如果要保留 `kv.clearAll()` 的用法，就只能把 cache 缓存给移除了，改回之前的实现方式。

**Comment by ljphawk** [comment]
仔细想了一下，以目前的方式好像是无解，只能去除cache，但cache的存在和设计感觉也是挺有意思的。再问一个问题哈，如何在现有委托模式的基础上，动态改变key，比如有个值 我名字为  switch,但我希望她关联用户id，我期望他动态变成switch1001

**Comment by DylanCaiCoding** [comment]
最新的 1.2.15 版本移除了 cache 和增加了 LiveData 的用法，可通过 LiveData 动态修改 key，可看下[更新日志](https://github.com/DylanCaiCoding/MMKV-KTX/releases)。

用法如下：
```kotlin
object DataRepository : MMKVOwner {
  val name by mmkvString().asLiveData()
}

DataRepository.name.key = "new_key"

DataRepository.name.observe(this) {
  // ...
}
```
