### ISSUE TITLE
再提个bug，多进程初始化的情况

### ISSUE THREAD

**Issue by ljphawk** [DylanCaiCoding/MMKV-KTX#6]
如果是多进程初始化，使用Initializer进行mmkv的初始化，但是如果再application的oncreate进行调用，没有判断是否是主进程的情况下，非主进程MMKVOwner.default就会为null

**Comment by DylanCaiCoding** [comment]
这就体现了 MMKVOwner 接口的意义了，重写 MMKVOwner 的 kv 属性，改成多进程的 MMKV 对象

```kotlin
object DataRepository : MMKVOwner {
  // ...
  
  override val kv = MMKV.mmkvWithID("InterProcessKV", MMKV.MULTI_PROCESS_MODE)
}
```
