### ISSUE TITLE
能提供MMKV初始化配置吗？

### ISSUE THREAD

**Issue by xuexixuexijpg** [DylanCaiCoding/MMKV-KTX#8]
我看初始化用的是startup延迟初始化？而且只有一个默认初始化，如果我想指定MMKV文件存储位置或其他配置的话，这个我要自己手动初始化？

**Comment by DylanCaiCoding** [comment]
对，目前 App Startup 只能省去默认初始化的代码，我再提供点 `<mata-data/>` 来配置存储位置和 log 等级吧。

```xml
<meta-data 
  android:name="mmkv_dir" 
  android:value="/mmkv_2" />

<meta-data 
  android:name="mmkv_log_level" 
  android:value="debug" />
```

还有其它的 `MMKV.initialize()` 配置需求吗？

**Comment by xuexixuexijpg** [comment]
> 对，目前 App Startup 只能省去默认初始化的代码，我再提供点 `<mata-data/>` 来配置存储位置和 log 等级吧。
> 
> ```
> <meta-data 
>   android:name="mmkv_dir" 
>   android:value="/mmkv_2" />
> 
> <meta-data 
>   android:name="mmkv_log_level" 
>   android:value="debug" />
> ```
> 
> 还有其它的 `MMKV.initialize()` 配置需求吗？

没有了，感谢

**Comment by DylanCaiCoding** [comment]
抱歉，拖了比较久，2.0.1 版本支持上面说的 `<meta-data./>` 配置了，还支持 `asMap()` 转成 `map` 来使用，可以根据不同的 id 保存不同的数据
