### ISSUE TITLE
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.musicho.andro-jmxJoVRLaDJ_0L_kHWTQdA==/base.apk"],nativeLibraryDirectories=[/data/app/com.musicho.andro-jmxJoVRLaDJ_0L_kHWTQdA==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libmmkv.so"

### ISSUE THREAD

**Issue by aikorola** [DylanCaiCoding/MMKV-KTX#9]
在firebase上看到的崩溃，不知道怎么处理，麻烦大佬看下，我现在是在build.gradle下加了
`ndk {
            //APP的build.gradle设置支持的SO库架构
            abiFilters 'armeabi-v7a', "armeabi", "arm64-v8a", 'x86_64'
        }`

**完整崩溃日志**
[com.musicho.andro_issue_61117a57833c6664c9bdb1c17f8b13bf_crash_session_6619E09201CB00011A5473926F8486A4_DNE_0_v2_stacktrace.txt](https://github.com/DylanCaiCoding/MMKV-KTX/files/15009251/com.musicho.andro_issue_61117a57833c6664c9bdb1c17f8b13bf_crash_session_6619E09201CB00011A5473926F8486A4_DNE_0_v2_stacktrace.txt)

**Comment by DylanCaiCoding** [comment]
之前有遇到类似的，好像升级 mmkv 版本后没看到了。

```
api('com.github.DylanCaiCoding:MMKV-KTX:1.2.16') {
  exclude(group: "com.tencent", module: "mmkv-static")
}
api("com.tencent:mmkv-static:1.3.9")
```

个人最近发布了 2.0.1 版本，内置的是 mmkv v2.0.1 版本，也可以升级这个版本试下。支持了 `map` 用法，根据不同 id 来缓存数据。

**Comment by Caleb-Rainbow** [comment]
2.0.1版本放弃了对32位系统的支持，目前1.3的LTS版本保留对32位系统的支持，希望能适配下1.3的LTS版本[https://github.com/Tencent/MMKV/releases/tag/v1.3.11](url)

**Comment by sy5251** [comment]
java.lang.RuntimeException:Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader...couldn't find "libmmkv.so"

已经确定了，2.0.1版本对 部分手机会闪退，占比大概2-5%的设备，应该是32位系统导致的
